# Generated by Django 4.0.3 on 2022-05-01 16:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdd', '0002_ingeprev_delete_entreprise_alter_affaire_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingeprev',
            name='Cle',
            field=models.CharField(blank=True, max_length=10, verbose_name='Clé'),
        ),
        migrations.AddField(
            model_name='ingeprev',
            name='Code_BIC',
            field=models.CharField(blank=True, max_length=20, verbose_name='Code BIC'),
        ),
        migrations.AddField(
            model_name='ingeprev',
            name='Code_Banque',
            field=models.IntegerField(blank=True, null=True, verbose_name='Code Banque'),
        ),
        migrations.AddField(
            model_name='ingeprev',
            name='Code_Guichet',
            field=models.IntegerField(blank=True, null=True, verbose_name='Code Guichet'),
        ),
        migrations.AddField(
            model_name='ingeprev',
            name='Nom_Banque',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nom de la Banque'),
        ),
        migrations.AddField(
            model_name='ingeprev',
            name='Num_Compte',
            field=models.IntegerField(blank=True, null=True, verbose_name='Numéro de Compte'),
        ),
        migrations.AddField(
            model_name='ingeprev',
            name='Tel_Banque',
            field=models.CharField(blank=True, max_length=16, validators=[django.core.validators.RegexValidator(message='Un numero de téléphone est attendu.', regex='^\\+?1?\\d{8,15}$')], verbose_name='Numéro de Téléphone de la banque'),
        ),
        migrations.AlterField(
            model_name='ingeprev',
            name='IBAN',
            field=models.CharField(blank=True, max_length=50, verbose_name='IBAN'),
        ),
    ]
