# Generated by Django 4.0.3 on 2022-05-02 10:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdd', '0003_ingeprev_cle_ingeprev_code_bic_ingeprev_code_banque_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='Date_Previsionnelle',
            field=models.DateField(blank=True, default=datetime.date.today, verbose_name='Date prévisionnelle affaire'),
        ),
    ]
