# Generated by Django 4.0.3 on 2022-05-02 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bdd', '0004_facture_date_previsionnelle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facture',
            name='Date_Previsionnelle',
        ),
    ]
