# Generated by Django 4.0.3 on 2022-05-02 15:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdd', '0005_remove_facture_date_previsionnelle'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='Date_Relance6',
            field=models.DateField(blank=True, default=datetime.date.today, verbose_name='Date de relance6 - contentieux'),
        ),
    ]
