# Generated by Django 4.0.3 on 2022-05-02 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdd', '0006_facture_date_relance6'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingeprev',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
