# Generated by Django 4.0.3 on 2022-05-03 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdd', '0007_ingeprev_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingeprev',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
