# Generated by Django 4.0.3 on 2022-05-09 17:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdd', '0008_alter_ingeprev_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='Avoir_Lie',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='affaire',
            name='Type_Affaire',
            field=models.CharField(blank=True, choices=[('C', 'Conseil'), ('AMO', 'AMO'), ('DA', 'Diag/Audit')], default='C', max_length=12, verbose_name="Type d'Affaire"),
        ),
        migrations.AlterField(
            model_name='affaire',
            name='soldee',
            field=models.BooleanField(default='False', verbose_name='Archivée'),
        ),
        migrations.AlterField(
            model_name='envoi_facture',
            name='Adresse',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='envoi_facture',
            name='CP',
            field=models.CharField(blank=True, max_length=5, validators=[django.core.validators.RegexValidator(message='le code postal doit être composé de 5 chiffres.', regex='^[0-9]+$')], verbose_name='Code postal'),
        ),
        migrations.AlterField(
            model_name='envoi_facture',
            name='Mode_Paiement',
            field=models.CharField(choices=[('ND', 'Non défini'), ('VI', 'Virement'), ('CH', 'Chèque'), ('CB', 'Carte Bancaire'), ('ES', 'Espèces')], default='VI', max_length=20, verbose_name='Mode de Paiement'),
        ),
        migrations.AlterField(
            model_name='envoi_facture',
            name='Ville',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='facture',
            name='Denomination_Facture',
            field=models.CharField(max_length=50, verbose_name='Dénomination sociale Facture'),
        ),
        migrations.AlterField(
            model_name='infoemail',
            name='Subject',
            field=models.CharField(default='Facture Ingeprev', max_length=100, verbose_name='Sujet'),
        ),
    ]
