# Generated by Django 4.0.3 on 2022-05-09 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdd', '0009_facture_avoir_lie_alter_affaire_type_affaire_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='Facture_Liee',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
