# Generated by Django 4.0.3 on 2022-05-10 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdd', '0010_facture_facture_liee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facture',
            name='Avoir_Lie',
        ),
        migrations.AlterField(
            model_name='facture',
            name='Facture_Liee',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Facture liée'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='Montant_Facture_HT',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Montant Facture H.T.'),
        ),
    ]
