# Generated by Django 4.0.3 on 2022-08-22 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdd', '0011_remove_facture_avoir_lie_alter_facture_facture_liee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='Num_Suivi',
            field=models.CharField(blank=True, default='A préciser', max_length=20, verbose_name='Numéro Suivi - Relance 2'),
        ),
        migrations.AddField(
            model_name='infoemail',
            name='Suivi',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='facture',
            name='Num_RAR',
            field=models.CharField(blank=True, default='A préciser', max_length=20, verbose_name='Numéro RAR - Relance 3'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='Num_RAR_Demeure',
            field=models.CharField(blank=True, default='A préciser', max_length=20, verbose_name='Numéro RAR - Mise en demeure (Relance 4)'),
        ),
        migrations.AlterField(
            model_name='infoemail',
            name='RAR',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
