# Generated by Django 4.0.3 on 2022-08-22 15:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdd', '0012_facture_num_suivi_infoemail_suivi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='Date_Relance1',
            field=models.DateField(blank=True, default=datetime.date.today, verbose_name='Date de relance1 - relance par mail - J'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='Date_Relance2',
            field=models.DateField(blank=True, default=datetime.date.today, verbose_name='Date de relance2 - relance courrier suivi - J+30'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='Date_Relance3',
            field=models.DateField(blank=True, default=datetime.date.today, verbose_name='Date de relance3 - relance RAR - J+60'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='Date_Relance4',
            field=models.DateField(blank=True, default=datetime.date.today, verbose_name='Date de relance4 - nise en demeure - J+90'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='Date_Relance5',
            field=models.DateField(blank=True, default=datetime.date.today, verbose_name='Date de relance5 - conciliation - J+100'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='Date_Relance6',
            field=models.DateField(blank=True, default=datetime.date.today, verbose_name='Date de relance6 - assignation - J+220'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='Num_RAR',
            field=models.CharField(blank=True, default='A préciser', max_length=25, verbose_name='Numéro RAR - Relance3'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='Num_RAR_Demeure',
            field=models.CharField(blank=True, default='A préciser', max_length=25, verbose_name='Numéro RAR - Relance4 (Mise en demeure)'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='Num_Suivi',
            field=models.CharField(blank=True, default='A préciser', max_length=20, verbose_name='Numéro Suivi - Relance2'),
        ),
    ]
