# Generated by Django 4.0.3 on 2022-09-07 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdd', '0013_alter_facture_date_relance1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='affaire',
            name='Ref_Client',
            field=models.CharField(blank=True, max_length=50, verbose_name='Référence Client à rappeler'),
        ),
    ]
