# Generated by Django 4.0.3 on 2022-09-07 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdd', '0014_affaire_ref_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='Ref_Client',
            field=models.CharField(blank=True, max_length=50, verbose_name='Référence Client à rappeler'),
        ),
    ]
