# Generated by Django 4.0.3 on 2022-09-07 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdd', '0015_facture_ref_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envoi_facture',
            name='Delais_Paiement',
            field=models.CharField(choices=[('30', '30'), ('60', '60')], default='30', max_length=3, verbose_name='Délais de Paiement (en jours)'),
        ),
        migrations.AlterField(
            model_name='envoi_facture',
            name='Fin_Mois',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Oui', max_length=3, verbose_name='Fin de Mois'),
        ),
    ]
