# Generated by Django 4.0.3 on 2022-09-07 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdd', '0016_alter_envoi_facture_delais_paiement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingeprev',
            name='Code_Banque',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Code Banque'),
        ),
        migrations.AlterField(
            model_name='ingeprev',
            name='Code_Guichet',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Code Guichet'),
        ),
        migrations.AlterField(
            model_name='ingeprev',
            name='Num_Compte',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Numéro de Compte'),
        ),
    ]
