# Generated by Django 4.0.5 on 2022-09-07 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdd', '0018_alter_ingeprev_num_compte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingeprev',
            name='Code_Banque',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Code Banque (saisir sans espaces)'),
        ),
        migrations.AlterField(
            model_name='ingeprev',
            name='Code_Guichet',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Code Guichet (saisir sans espaces)'),
        ),
        migrations.AlterField(
            model_name='ingeprev',
            name='IBAN',
            field=models.CharField(blank=True, max_length=50, verbose_name='IBAN (saisir sans espaces)'),
        ),
        migrations.AlterField(
            model_name='ingeprev',
            name='Num_Compte',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Numéro de Compte (saisir sans espaces)'),
        ),
    ]
