# Generated by Django 4.0.3 on 2022-10-17 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdd', '0018_alter_ingeprev_num_compte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='Denomination_Sociale',
            field=models.CharField(max_length=150, verbose_name='Dénomination sociale'),
        ),
        migrations.AlterField(
            model_name='envoi_facture',
            name='Denomination_Sociale',
            field=models.CharField(max_length=150, verbose_name='Dénomination sociale'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='Ref_Client',
            field=models.CharField(blank=True, max_length=150, verbose_name='Référence Client à rappeler'),
        ),
        migrations.AlterField(
            model_name='ingeprev',
            name='Code_Banque',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Code Banque (saisir sans espaces)'),
        ),
        migrations.AlterField(
            model_name='ingeprev',
            name='Code_Guichet',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Code Guichet (saisir sans espaces)'),
        ),
        migrations.AlterField(
            model_name='ingeprev',
            name='IBAN',
            field=models.CharField(blank=True, max_length=50, verbose_name='IBAN (saisir sans espaces)'),
        ),
        migrations.AlterField(
            model_name='ingeprev',
            name='Num_Compte',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Numéro de Compte (saisir sans espaces)'),
        ),
        migrations.AlterField(
            model_name='ingeprev',
            name='SIRET',
            field=models.CharField(blank=True, max_length=50, verbose_name='N° de SIRET (saisir sans espace)'),
        ),
    ]
