# Generated by Django 4.0.5 on 2022-09-07 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdd', '0019_alter_ingeprev_code_banque_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingeprev',
            name='SIRET',
            field=models.CharField(blank=True, max_length=50, verbose_name='N° de SIRET (saisir sans espace)'),
        ),
    ]
