# Generated by Django 4.0.3 on 2022-10-17 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdd', '0019_alter_client_denomination_sociale_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affaire',
            name='Ref_Client',
            field=models.CharField(blank=True, max_length=150, verbose_name='Référence Client à rappeler'),
        ),
    ]
