# Generated by Django 4.0.5 on 2022-09-10 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdd', '0020_alter_ingeprev_siret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='Denomination_Sociale',
            field=models.CharField(max_length=150, verbose_name='Dénomination sociale'),
        ),
        migrations.AlterField(
            model_name='envoi_facture',
            name='Denomination_Sociale',
            field=models.CharField(max_length=150, verbose_name='Dénomination sociale'),
        ),
    ]
