# Generated by Django 4.0.5 on 2022-10-17 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bdd', '0020_alter_affaire_ref_client'),
        ('bdd', '0021_alter_client_denomination_sociale_and_more'),
    ]

    operations = [
    ]
