# Generated by Django 4.0.3 on 2022-10-23 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdd', '0022_merge_20221017_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(upload_to='tmp', verbose_name='Attachment'),
        ),
    ]
